m1n6s200_driver:
  joint_state_controller:
    publish_rate: 1000
    type: joint_state_controller/JointStateController

  arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - m1n6s200_joint_1
      - m1n6s200_joint_2
      - m1n6s200_joint_3
      - m1n6s200_joint_4
      - m1n6s200_joint_5
      - m1n6s200_joint_6

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default
      m1n6s200_joint_1:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
      m1n6s200_joint_2:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      m1n6s200_joint_3:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
      m1n6s200_joint_4:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      m1n6s200_joint_5:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
      m1n6s200_joint_6:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified

    gains: # Required because we're controlling an effort interface
      m1n6s200_joint_1: {p: 200.0, d: 0.3, i: 24.0, i_clamp:  8.0}
      m1n6s200_joint_2: {p: 300.0, d: 0.4, i: 36.0, i_clamp: 16.0}
      m1n6s200_joint_3: {p: 300.0, d: 0.4, i: 36.0, i_clamp: 16.0}
      m1n6s200_joint_4: {p: 200.0, d: 0.3, i: 24.0, i_clamp:  4.0}
      m1n6s200_joint_5: {p: 150.0, d: 0.2, i: 18.0, i_clamp:  4.0}
      m1n6s200_joint_6: {p: 100.0, d: 0.2, i: 12.0, i_clamp:  1.0}

    state_publish_rate:  250            # Override default
    action_monitor_rate:  50            # Override default
    stop_trajectory_duration: 0         # Override default

  gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - m1n6s200_joint_finger_1
      - m1n6s200_joint_finger_2

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default
      m1n6s200_joint_finger_1:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
      m1n6s200_joint_finger_2:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified

    gains: # Required because we're controlling an effort interface
      m1n6s200_joint_finger_1: {p: 10.0, d: 0.01, i: 0.01, i_clamp: 1.0}
      m1n6s200_joint_finger_2: {p: 10.0, d: 0.01, i: 0.01, i_clamp: 1.0}

    state_publish_rate:  50            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
